-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\motor_controller\motor_con_ip_src_Subsystem.vhd
-- Created: 2017-11-07 15:16:50
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: motor_con_ip_src_Subsystem
-- Source Path: motor_controller/Subsystem
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY motor_con_ip_src_Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Frequency_Hz                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        PWM                               :   OUT   std_logic
        );
END motor_con_ip_src_Subsystem;


ARCHITECTURE rtl OF motor_con_ip_src_Subsystem IS

  -- Component Declarations
  COMPONENT motor_con_ip_src_Motor_Controller_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Frequency                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          pwm                             :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : motor_con_ip_src_Motor_Controller_block
    USE ENTITY work.motor_con_ip_src_Motor_Controller_block(rtl);

  -- Signals
  SIGNAL pwm_1                            : std_logic;

BEGIN
  u_Motor_Controller : motor_con_ip_src_Motor_Controller_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Frequency => Frequency_Hz,  -- uint32
              pwm => pwm_1
              );

  PWM <= pwm_1;

END rtl;

