-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\detect_rising_edge\Rising_Edge_Detector.vhd
-- Created: 2017-11-01 03:06:16
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.06
-- Target subsystem base rate: 0.06
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.06
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- out_rsvd                      ce_out        0.06
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Rising_Edge_Detector
-- Source Path: detect_rising_edge/Rising Edge Detector
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Rising_Edge_Detector IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        in_rsvd                           :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        out_rsvd                          :   OUT   std_logic
        );
END Rising_Edge_Detector;


ARCHITECTURE rtl OF Rising_Edge_Detector IS

  -- Component Declarations
  COMPONENT Detect_Rise_Positive
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          U                               :   IN    std_logic;
          Y                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Detect_Rise_Positive
    USE ENTITY work.Detect_Rise_Positive(rtl);

  -- Signals
  SIGNAL Detect_Rise_Positive_out1        : std_logic;

BEGIN
  u_Detect_Rise_Positive : Detect_Rise_Positive
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              U => in_rsvd,
              Y => Detect_Rise_Positive_out1
              );

  ce_out <= clk_enable;

  out_rsvd <= Detect_Rise_Positive_out1;

END rtl;

