-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\motor_controller\motor_con_ip_src_Motor_Controller_block.vhd
-- Created: 2017-11-07 15:16:50
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: motor_con_ip_src_Motor_Controller_block
-- Source Path: motor_controller/Subsystem/Motor Controller
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY motor_con_ip_src_Motor_Controller_block IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Frequency                         :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        pwm                               :   OUT   std_logic
        );
END motor_con_ip_src_Motor_Controller_block;


ARCHITECTURE rtl OF motor_con_ip_src_Motor_Controller_block IS

  -- Component Declarations
  COMPONENT motor_con_ip_src_Chart
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          ESCPeriod                       :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          pw                              :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          pwm                             :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : motor_con_ip_src_Chart
    USE ENTITY work.motor_con_ip_src_Chart(rtl);

  -- Signals
  SIGNAL ESCPeriod_out1                   : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Frequency_unsigned               : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL Gain_mul_temp                    : unsigned(63 DOWNTO 0);  -- ufix64_En26
  SIGNAL Gain_out1                        : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  u_Chart : motor_con_ip_src_Chart
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              ESCPeriod => std_logic_vector(ESCPeriod_out1),  -- uint32
              pw => std_logic_vector(Gain_out1),  -- uint32
              pwm => pwm
              );

  ESCPeriod_out1 <= to_unsigned(125000, 32);

  Frequency_unsigned <= unsigned(Frequency);

  -- CSD Encoding (3355443200) : 011001000000000000000000000000000; Cost (Adders) = 2
  Gain_mul_temp <= (resize(Frequency_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64) + resize(Frequency_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64)) + resize(Frequency_unsigned & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);
  Gain_out1 <= Gain_mul_temp(57 DOWNTO 26);


END rtl;

