-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\motor_controller\motor_con_ip_src_motor_controller.vhd
-- Created: 2017-11-07 15:16:50
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- PWM                           ce_out        0.2
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: motor_con_ip_src_motor_controller
-- Source Path: motor_controller
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY motor_con_ip_src_motor_controller IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        PWM                               :   OUT   std_logic
        );
END motor_con_ip_src_motor_controller;


ARCHITECTURE rtl OF motor_con_ip_src_motor_controller IS

  -- Component Declarations
  COMPONENT motor_con_ip_src_Subsystem
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Frequency_Hz                    :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          PWM                             :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : motor_con_ip_src_Subsystem
    USE ENTITY work.motor_con_ip_src_Subsystem(rtl);

  -- Signals
  SIGNAL Constant_out1                    : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL pwm_1                            : std_logic;

BEGIN
  -- PWM Based on Sample time of 100uS or 10kHz Frequency
  -- Provide PWM of 500uS to 2000uS based on 400Hz (2.5ms period)
  -- 500Hz = 2ms or 2000uS period
  -- 
  -- Pulse Width in Microseconds

  u_Subsystem : motor_con_ip_src_Subsystem
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Frequency_Hz => std_logic_vector(Constant_out1),  -- uint32
              PWM => pwm_1
              );

  Constant_out1 <= to_unsigned(1500, 32);

  ce_out <= clk_enable;


  PWM <= pwm_1;

END rtl;

