-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\motor_controller\motor_con_ip_src_motor_controller_pkg.vhd
-- Created: 2017-11-07 15:16:50
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE motor_con_ip_src_motor_controller_pkg IS
  TYPE T_state_type_is_Chart IS (IN_off, IN_on);
END motor_con_ip_src_motor_controller_pkg;

