-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\detect_rising_edge\Subsystem.vhd
-- Created: 2017-11-01 02:52:09
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0.2
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0.2
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Subsystem
-- Source Path: detect_rising_edge/Subsystem
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Subsystem IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic
        );
END Subsystem;


ARCHITECTURE rtl OF Subsystem IS

  -- Component Declarations
  COMPONENT Detect_Rise_Nonnegative
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          U                               :   IN    std_logic;
          Y                               :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Detect_Rise_Nonnegative
    USE ENTITY work.Detect_Rise_Nonnegative(rtl);

  -- Signals
  SIGNAL Detect_Rise_Nonnegative_out1     : std_logic;

BEGIN
  u_Detect_Rise_Nonnegative : Detect_Rise_Nonnegative
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              U => In1,
              Y => Detect_Rise_Nonnegative_out1
              );

  ce_out <= clk_enable;

  Out1 <= Detect_Rise_Nonnegative_out1;

END rtl;

