-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mpu6050_working\ADXL345_ip_src_I2C_MPU6050_IP_pkg.vhd
-- Created: 2017-12-03 22:48:36
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE ADXL345_ip_src_I2C_MPU6050_IP_pkg IS
  TYPE T_state_type_is_MPU6050_Interface IS (IN_Valid, IN_cfgDone, IN_check_cfg, IN_debuggingState, IN_getDEVID, IN_getRegData, IN_idle, IN_init, IN_readAccelXoutH, IN_readAccelXoutL, IN_readAccelYoutH, IN_readAccelZoutH, IN_readAccelZoutL, IN_readDEVID, IN_readGyroXoutH, IN_readGyroXoutL, IN_readGyroYoutH, IN_readGyroYoutL, IN_readGyroZoutH, IN_readGyroZoutL, IN_readPwrManagement1, IN_readUserRegData, IN_readWhoAmI1, IN_setupFS_SEL, IN_setupReadAccelXoutH, IN_setupReadAccelXoutL, IN_setupReadAccelYoutH, IN_setupReadAccelYoutL, IN_setupReadAccelZoutH, IN_setupReadAccelZoutL, IN_setupReadGyroXoutH, IN_setupReadGyroXoutL, IN_setupReadGyroYoutH, IN_setupReadGyroYoutL, IN_setupReadGyroZoutH, IN_setupReadGyroZoutL, IN_setupReadPwrMgmt1, IN_setupReadWhoAmI, IN_setupWritePwrMgmt1, IN_waitforNotBusy0, IN_waitforNotBusy01, IN_waitforNotBusy03, IN_waitforNotBusy04, IN_waitforNotBusy05, IN_waitforNotBusy06, IN_waitforNotBusy07, IN_waitforNotBusy1, IN_waitforNotBusy2, IN_waitforNotBusy3, IN_waitforNotBusy5, IN_waitforNotBusya1, IN_waitforNotBusya3, IN_waitforNotBusya4, IN_waitforNotBusya5, IN_waitforNotBusya6, IN_waitforNotBusya7, b_IN_readGyroYoutL, b_IN_waitforNotBusy1);
  TYPE T_state_type_is_i2c_mstr IS (IN_Increment_Byte_count1, IN_ack_addr_m, IN_ack_addr_m_cnf, IN_ack_addrm1, IN_ack_data, IN_ack_end, IN_ack_end1, IN_ack_recv_wr, IN_ack_recv_wr1, IN_ack_recv_wr2, IN_ack_recv_wr3, IN_ack_slv, IN_ack_slv1, IN_ack_slv_cnf1, IN_ack_wr_p, IN_ack_wr_p2, IN_cmd_reg_addr_n, IN_cmd_reg_addr_p, IN_cmd_reg_data_n, IN_cmd_reg_data_p, IN_cmd_reg_read_data_n, IN_cmd_reg_read_data_p, IN_cmd_slave_addr_n, IN_cmd_slave_addr_n1, IN_cmd_slave_addr_p, IN_cmd_slave_addr_p1, IN_delay, IN_error_ack, IN_idle, IN_mastr_ack_data, IN_mastr_ack_data_cnf, IN_mastr_ack_data_cnf1, IN_read_n, IN_read_p, IN_ready, IN_ready_repeated, IN_ready_repeated_dummy, IN_repeat_strt_n, IN_repeat_strt_p, IN_scl_ext_n, IN_scl_ext_p, IN_start_n, IN_start_p, IN_stop, IN_stop_ext, IN_write_n, IN_write_p);
END ADXL345_ip_src_I2C_MPU6050_IP_pkg;

