-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mpu6050\I2C_MPU60_ip_src_I2C_MPU6050_IP_pkg.vhd
-- Created: 2017-11-10 18:20:45
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE I2C_MPU60_ip_src_I2C_MPU6050_IP_pkg IS
  TYPE T_state_type_is_MPU6050_Interface IS (IN_Valid, IN_accelX_LSB, IN_accelX_MSB, IN_accelY_LSB, IN_accelY_MSB, IN_accelZ_LSB, IN_accelZ_MSB, IN_cfgDone, IN_check_cfg, IN_getDEVID, IN_getRegData, IN_gyroX_LSB, IN_gyroX_MSB, IN_gyroY_LSB, IN_gyroY_MSB, IN_gyroZ_LSB, IN_gyroZ_MSB, IN_idle, IN_init, IN_readDEVID, IN_readUserRegData, IN_read_accelX_registers0, IN_read_gyroX_registers0, IN_setPwrMode, IN_toggle, IN_toggle1, IN_toggle2, IN_toggle3, IN_toggle4, IN_waitforNotBusy1, IN_waitforNotBusy2, IN_waitforNotBusy5, b_IN_toggle, b_IN_toggle1, b_IN_toggle2, b_IN_toggle3, b_IN_toggle4, b_IN_waitforNotBusy2, c_IN_waitforNotBusy2);
  TYPE T_state_type_is_i2c_mstr IS (IN_Increment_Byte_count1, IN_ack_addr_m, IN_ack_addr_m_cnf, IN_ack_addrm1, IN_ack_data, IN_ack_end, IN_ack_end1, IN_ack_recv_wr, IN_ack_recv_wr1, IN_ack_recv_wr2, IN_ack_recv_wr3, IN_ack_slv, IN_ack_slv1, IN_ack_slv_cnf1, IN_ack_wr_p, IN_ack_wr_p2, IN_cmd_reg_addr_n, IN_cmd_reg_addr_p, IN_cmd_reg_data_n, IN_cmd_reg_data_p, IN_cmd_reg_read_data_n, IN_cmd_reg_read_data_p, IN_cmd_slave_addr_n, IN_cmd_slave_addr_n1, IN_cmd_slave_addr_p, IN_cmd_slave_addr_p1, IN_delay, IN_error_ack, IN_idle, IN_mastr_ack_data, IN_mastr_ack_data_cnf, IN_mastr_ack_data_cnf1, IN_read_n, IN_read_p, IN_ready, IN_ready_repeated, IN_ready_repeated_dummy, IN_repeat_strt_n, IN_repeat_strt_p, IN_scl_ext_n, IN_scl_ext_p, IN_start_n, IN_start_p, IN_stop, IN_stop_ext, IN_write_n, IN_write_p);
END I2C_MPU60_ip_src_I2C_MPU6050_IP_pkg;

