-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\mpu6050\ADXL345_ip_src_MATLAB_Function.vhd
-- Created: 2017-12-01 18:55:10
-- 
-- Generated by MATLAB 9.2 and HDL Coder 3.10
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ADXL345_ip_src_MATLAB_Function
-- Source Path: mpu6050/I2C_MPU6050_IP/MATLAB Function
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ADXL345_ip_src_MATLAB_Function IS
  PORT( oldLedArr                         :   IN    std_logic_vector(0 TO 7);  -- boolean [8]
        oldTrigUpdate                     :   IN    std_logic;
        tmp                               :   IN    std_logic;
        config                            :   IN    std_logic;
        checkConfig                       :   IN    std_logic;
        readGyro                          :   IN    std_logic;
        readAccel                         :   IN    std_logic;
        valid                             :   IN    std_logic;
        readDevice                        :   IN    std_logic;
        tmpHere                           :   IN    std_logic;
        dataRead                          :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        update                            :   IN    std_logic;
        modeSw1                           :   IN    std_logic;
        ledArr                            :   OUT   std_logic_vector(0 TO 7);  -- boolean [8]
        trigUpdate                        :   OUT   std_logic
        );
END ADXL345_ip_src_MATLAB_Function;


ARCHITECTURE rtl OF ADXL345_ip_src_MATLAB_Function IS

  -- Signals
  SIGNAL dataRead_unsigned                : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  dataRead_unsigned <= unsigned(dataRead);

  MATLAB_Function_output : PROCESS (oldLedArr, oldTrigUpdate, tmp, config, checkConfig, readGyro, readAccel, valid,
       readDevice, tmpHere, dataRead_unsigned, update, modeSw1)
  BEGIN
    --MATLAB Function 'I2C_MPU6050_IP/MATLAB Function': '<S3>:1'
    IF (update AND ( NOT oldTrigUpdate)) = '1' THEN 
      --'<S3>:1:2'
      --'<S3>:1:2'
      --sw0
      --'<S3>:1:3'
      ledArr <= (OTHERS => '0');
      IF modeSw1 = '1' THEN 
        --'<S3>:1:4'
        --sw1 = 0
        --'<S3>:1:5'
        ledArr(0) <= tmp;
        -- led0
        --'<S3>:1:6'
        ledArr(1) <= config;
        --'<S3>:1:7'
        ledArr(2) <= checkConfig;
        --'<S3>:1:8'
        ledArr(3) <= readGyro;
        --'<S3>:1:9'
        ledArr(4) <= readAccel;
        --'<S3>:1:10'
        ledArr(5) <= valid;
        --'<S3>:1:11'
        ledArr(6) <= readDevice;
        --'<S3>:1:12'
        ledArr(7) <= tmpHere;
        -- led7
      ELSE 
        -- mode 1 sw1 = 1
        --'<S3>:1:14'
        IF dataRead_unsigned(0) /= '0' THEN 
          ledArr(0) <= '1';
        ELSE 
          ledArr(0) <= '0';
        END IF;
        -- led0
        --'<S3>:1:15'
        IF dataRead_unsigned(1) /= '0' THEN 
          ledArr(1) <= '1';
        ELSE 
          ledArr(1) <= '0';
        END IF;
        --'<S3>:1:16'
        IF dataRead_unsigned(2) /= '0' THEN 
          ledArr(2) <= '1';
        ELSE 
          ledArr(2) <= '0';
        END IF;
        --'<S3>:1:17'
        IF dataRead_unsigned(3) /= '0' THEN 
          ledArr(3) <= '1';
        ELSE 
          ledArr(3) <= '0';
        END IF;
        --'<S3>:1:18'
        IF dataRead_unsigned(4) /= '0' THEN 
          ledArr(4) <= '1';
        ELSE 
          ledArr(4) <= '0';
        END IF;
        --'<S3>:1:19'
        IF dataRead_unsigned(5) /= '0' THEN 
          ledArr(5) <= '1';
        ELSE 
          ledArr(5) <= '0';
        END IF;
        --'<S3>:1:20'
        IF dataRead_unsigned(6) /= '0' THEN 
          ledArr(6) <= '1';
        ELSE 
          ledArr(6) <= '0';
        END IF;
        --'<S3>:1:21'
        IF dataRead_unsigned(7) /= '0' THEN 
          ledArr(7) <= '1';
        ELSE 
          ledArr(7) <= '0';
        END IF;
        -- led7
      END IF;
      --'<S3>:1:23'
      trigUpdate <= '1';
    ELSE 
      --'<S3>:1:25'
      ledArr <= oldLedArr;
      --'<S3>:1:26'
      trigUpdate <= '0';
    END IF;
  END PROCESS MATLAB_Function_output;


END rtl;

